project:
  type: website
resources:
  - assets/**
  - CV/**
website:
  title: "Alicia Franco-Martínez"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    logo: assets/logo.png
    right:
      - text: Person
        href: index.qmd
      - text: Researcher
        href: Researcher/Researcher.qmd
      - text: Visitor
        href: Visitor/Visitor.qmd
      - text: CV
        href: cv.qmd
      
format:
  html:
    anchor-sections: false
    mainfont: 'DM Serif Display'
    theme: [cosmo, styles.scss]
    css: styles.scss
